README.md, entrypoint.sh
=> fix: avoid #29 for keepFiles option

README.md
Flutter on the web is available with the beta channel now.
=> docs: Use Flutter beta channel

Dockerfile, entrypoint.sh
=> feat: ignore .git and .github

entrypoint.sh
=> fix: link to commit hash for external deployment

.github/workflows/test-action.yml, src/set-tokens.ts
log: https://github.com/peaceiris/actions-gh-pages/commits/gh-pages
=> feat: Add getHomeDir() for windows

.github/workflows/pages-status-check.yml
cf. https://github.com/fastai/fastpages/blob/9ca83a401862ef7da0689123c78c0e68a445b983/.github/workflows/gh-page.yaml
=> ci: Add deployment status check workflow

src/main.ts
=> fix: skip on fork if pull_request

src/main.ts
=> fix: skip on fork

src/main.ts
PR is pretty straightforward, didn't add any tests because the functionality added is simple enough.
=> Implement #165

README.md
Use the official way of installation.
=> docs: Improve Elm example

README.md
There were some issues, it was impossible to get it working just with a simple copy/paste
=> Updating Docusaurus config to make it work

README.md
- Add on.push.paths
- Add defaults.run.working-directory
- https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#defaultsrun
- https://github.blog/changelog/2020-04-15-github-actions-new-workflow-features/
CC @deimosfr
=> docs: Enhance Docusaurus example workflow

README.md
To separate caches into each workflow. (Main project and website project)
=> docs: Enhance cache key

.github/workflows/test.yml
cf. #268
- Add test job for ubuntu 20.04
- Bumps mdBook from 0.3.6 to 0.3.7
=> ci: Add test-ubuntu-20.04 job

.github/workflows/test.yml, README.md, __tests__/get-inputs.test.ts, __tests__/git-utils.test.ts, action.yml, src/get-inputs.ts, src/git-utils.ts, src/interfaces.ts, src/main.ts
=> feat: Add full_commit_message

README.md
cf. https://classic.yarnpkg.com/en/docs/cli/install
=> docs: Use yarn install --frozen-lockfile

README.md
[Keeping your dependencies updated automatically - GitHub Docs](https://docs.github.com/en/github/administering-a-repository/keeping-your-dependencies-updated-automatically)
=> docs: Add dependabot.yml example

README.md
=> docs: add notes #349

README.md
=> fix sample in README: change setup-node from v2 to v2.1.0

.github/workflows/codeql.yml, .github/workflows/dev-image.yml, .github/workflows/test.yml, release.sh
cf.
- https://github.com/actions/toolkit/issues/514
- https://github.com/ethomson/retarget_prs
=> chore: change default branch from master to main

src/git-utils.ts
=> fix: KeepFiles behaviour when DestinationDir has dir

src/git-utils.ts
https://github.com/peaceiris/actions-gh-pages/issues/410#issuecomment-663507581
=> fix: set full path of publishing assets

Dockerfile
```Dockerfile
ENV LANG="C.UTF-8"
ENV ImageVersion="20200625.0"
ENV GITHUB_API_URL="https://api.github.com"
ENV RUNNER_TOOL_CACHE="/opt/hostedtoolcache"
ENV GITHUB_REPOSITORY_OWNER="peaceiris"
ENV GITHUB_ACTIONS="true"
```
=> ci: add env

Dockerfile
git config --global init.defaultBranch main
https://github.blog/2020-07-27-highlights-from-git-2-28/
=> ci: Set default branch to main

README.md
https://github.com/peaceiris/actions-gh-pages/issues/324#issuecomment-779218091
=> docs: Improve description of destination_dir and keep_files

src/get-inputs.ts
Reduce redundancy and improve readability
=> refactor(get-inputs): add isBoolean

src/set-tokens.ts
https://github.blog/2023-03-23-we-updated-our-rsa-ssh-host-key/
- close https://github.com/peaceiris/actions-gh-pages/issues/878
=> fix: update known_hosts

.github/workflows/labeler.yml
Reverts peaceiris/actions-gh-pages#1039
=> Revert "chore(deps): update actions/labeler action to v5"

README.md
Intended to steer newcomers in the right direction as far as which versions of things to use
=> Actions examples: update to modern versions of actions
