peaceiris/actions-gh-pages

Dockerfile, entrypoint.sh
This re-uses the existing branch rather than always overwriting it with a new branch with single commit.
Signed-off-by: Michael Smith <michael.smith@puppet.com>
=> Fetch remote before testing whether the publish branch exists

README.md, entrypoint.sh
- [Authenticating with GitHub Apps | GitHub Developer Guide](https://developer.github.com/apps/building-github-apps/authenticating-with-github-apps/#http-based-git-access-by-an-installation)
=> Release v2.2.0

.github/workflows/docker-image-ci.yml, README.md, action.yml, entrypoint.sh
Apparently it was easier than I anticipated. This should address #21.
I'm not sure if you wanted to standardize around `env` or using the `inputs/`with` feature. I went with `inputs` because it allowed for a more explicit default value if it is not provided, and at the end of the day I think it all gets exposed the same way.
I also played with doing a more consolidated change to the bash file (not using `if`), but this way seems cleaner when it comes to non-zero exit codes from `git commit`. 
I did test this with my own site, and confirmed it works as expected when making website changes, when making non-website changes, and when the parameter is not defined (as it will be for pretty much everyone using this once it's released).
=> Optional empty commits

entrypoint.sh
When a publish branch exists and it has no files,
`git rm -r '*'` fails with
```
fatal: pathspec '*' did not match any files
```
[`--ignore-unmatch` option](https://git-scm.com/docs/git-rm#Documentation/git-rm.txt---ignore-unmatch) let git exit with a zero status in this case.
=> Fix: "git rm" fails when publish branch is empty

README.md, action.yml, entrypoint.sh
There is a use cases when you need to only add new files to GitHub pages and do not remove existing. E.g. when you host different versions of some JS lib from GitHub pages.
This PR adds an option to support this use case.
=> feat: new option keepFiles

README.md, entrypoint.sh
⚠ I didn't test this yet!
This PR addresses #35 .
* I added a new environment variable `PUBLISH_REPO` (format: `<username>/<repo>`) which is used to build the `remote_repo` strings.
* If `PUBLISH_REPO` is not set it will be set and initialized with `GITHUB_REPOSITORY`.
* If `PUBLISH_REPO` is different from `GITHUB_REPOSITORY` and `GITHUB_TOKEN` is used an error message will be printed and the script exits (the `GITHUB_TOKEN` is scoped to the repository which runs the action).
Example how this can be used:
```yaml
- name: Deploy
uses: peaceiris/actions-gh-pages@v2.4.0
env:
ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
PUBLISH_REPO: peaceiris/peaceiris.github.io
PUBLISH_BRANCH: master
PUBLISH_DIR: ./public
```
Any feedback is welcome 😊
=> feat: deploy to other repo (#35)

.github/workflows/docker-image-ci.yml, README.md, entrypoint.sh
=> Release: v2.5.0 script mode

README.md, action.yml, entrypoint.sh
=> feat: Add username and useremail options

README.md, action.yml, entrypoint.sh
Close #74
cf. #72 and #73
TODO
=> feat: Add commitMessage option

README.md, action.yml, entrypoint.sh
=> feat: Add tagName and tagMessage options

.github/workflows/test-action.yml, src/git-utils.ts, src/main.ts, src/set-tokens.ts
=> fix: Enable to create branch for first deployment

src/set-tokens.ts
GitHub might have started to supporting to trigger the GitHub Pages build event by GITHUB_TOKEN on public repositories. (We can already use the token on private repositories.) Be careful, there is no official announcement about this by GitHub.
cf. #9
=> [WIP] feat: Remove warning about GITHUB_TOKEN

README.md
=> docs: Put github_token as first example

.gitignore, README.md
=> Add example for Docusaurus docs.

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/proposal.md, .github/ISSUE_TEMPLATE/user_support.md
=> chore: Add user support issue template

README.md
https://github.com/JohnSundell/Publish
Close #227
=> docs: Add Swift Publish example

.github/workflows/test.yml
- feat: Support `ubuntu-16.04`
- ci: bump actions/upload-artifact from v1 to v2
- ci: fix artifact name for all matrix
=> feat: Support ubuntu-16.04

src/main.ts
cf. https://github.com/actions/toolkit/blob/master/docs/commands.md
=> feat: Fold logs using core.startGroup()

.github/workflows/test.yml
cf. [Add Ubuntu 20.04 focal · Issue #228 · actions/virtual-environments](https://github.com/actions/virtual-environments/issues/228#issuecomment-637362224)
=> ci: Add ubuntu-20.04 to matrix

README.md
- https://github.com/GitbookIO/gitbook
> As the efforts of the GitBook team are focused on the GitBook.com platform, the CLI is no longer under active development.
=> docs: remove gitbook

README.md
A GitHub Free Plan account cannot use the GitHub Pages in a private repository. To make your source contents private and deploy it with the GitHub Pages, you can deploy your site from a private repository to a public repository using the `external_repository`.
=> docs: Add use case

src/set-tokens.ts
In the current version, when trying to deploy to an external repository with
`github_token`, it fails with an inappropriate message.
Run workflow below:
```yaml
jobs:
deploy:
runs-on: ubuntu-latest
steps:
- run: hugo
- uses: peaceiris/actions-gh-pages@v3
with:
github_token: ${{ secrets.GITHUB_TOKEN }}
external_repository: sarisia/external-repository
publish_branch: master
publish_dir: ./public
```
and get:
```
Setup auth token
[INFO] setup GITHUB_TOKEN
##[error]Action failed with "You deploy from master to master"
```
I think this is inappropriate and difficult to identify the cause of failure, so
this PR changes check order in `setGithubToken()` to make error message more
intelligible.
=> fix check order in setGithubToken

.vscode/settings.json, __tests__/set-tokens.test.ts, package-lock.json, src/set-tokens.ts
- feat: add warning deploy_key on windows-latest
- Currently, the deploy_key option is not supported on the windows-latest.
- Related #87
Close #359
=> feat: enhance log message

README.md
[Events that trigger workflows - GitHub Docs](https://docs.github.com/en/actions/reference/events-that-trigger-workflows)
- on.schedule
- on.workflow_dispatch
=> docs: Add Schedule and Manual Deployment

__tests__/set-tokens.test.ts, src/set-tokens.ts
Ensure that the publish branch is treated as a complete name and not as a prefix.
=> fix false partial matches

README.md
=> docs: change default branch from master to main

src/git-utils.ts
Thanks for your great work. I have a use case where the tool to find the generated documentation is returning an absolute path. Instead of trying to calculate the relative paths by myself, I feel we can support absolute paths instead. This seems to be an easy change so I just made a PR. Please feel free to commit any further changes to this branch. This will close #242.
=> Allow absolute paths for publish_dir

README.md, __tests__/get-inputs.test.ts, __tests__/git-utils.test.ts, __tests__/utils.test.ts, action.yml, src/get-inputs.ts, src/git-utils.ts, src/interfaces.ts, src/utils.ts
=> feat: Add destination_dir option

src/git-utils.ts
This fixes #410 
The destination directory is not getting created using `fs.copyFileSync` (which is used in `io.cp`), so the code has to take care of that.
=> Fix deployment problems with destionationDir set

__tests__/get-inputs.test.ts, __tests__/git-utils.test.ts, action.yml, src/get-inputs.ts, src/git-utils.ts, src/interfaces.ts
Note that this option does not support regular expression currently.
Related to #163
=> feat: Add exclude_assets option

package-lock.json, package.json, src/git-utils.ts
Related to #163
https://github.com/actions/toolkit/tree/main/packages/glob
=> feat: exclude_assets supports glob patterns

Dockerfile
Change base docker image from `node:x.x.x-buster-slim` to `ubuntu:18.04`
The image size reduces from 1.05GB to 327MB
- Install Node.js via nodesource https://github.com/nodesource/distributions
- Install Git via ppa:git-core/ppa https://git-scm.com/download/linux
=> ci: change base image from Debian to Ubuntu 18.04

Dockerfile
```Dockerfile
DEBIAN_FRONTEND="noninteractive"
ImageVersion="20200717.1"
GITHUB_SERVER_URL="https://github.com"
GITHUB_GRAPHQL_URL="https://api.github.com/graphql"
GITHUB_ACTOR="peaceiris"
GITHUB_REPOSITORY="actions/pages"
RUNNER_OS="Linux"
RUNNER_USER="runner"
RUNNER_TEMP="/home/runner/work/_temp"
RUNNER_WORKSPACE="/home/runner/work/pages"
```
=> ci: Add actions runner env

src/git-utils.ts
=> refactor: Enhance log

README.md
the keep_files does not support working with the force_orphan with the v3.
Related to #455
=> docs: add note about keep_files and force_orphan

.github/dependabot.yml
[Configuration options for dependency updates - GitHub Docs](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates#allow)
=> ci: allow dependency-type production

README.md
Added a create-react-app example in case anyone is wondering how to use it with `actions-gh-pages`. It differs slightly from `Static Site Generators with Node.js`.
=> Add create-react-app example

.github/workflows/test.yml
> For public repositories, no token is needed
https://github.com/codecov/codecov-action
=> ci: remove CODECOV_TOKEN

.github/workflows/dev-image.yml, .github/workflows/test.yml
This will let people who forked this repository run CI without seeing misleading failures.
=> ci: Exclude writing actions on forks

package-lock.json, package.json
[npm 7 is now generally available! - The GitHub Blog](https://github.blog/2021-02-02-npm-7-is-now-generally-available/)
=> deps: Bump npm to v7

tsconfig.json
cf. [Node Target Mapping · microsoft/TypeScript Wiki](https://github.com/microsoft/TypeScript/wiki/Node-Target-Mapping)
=> build: Set target to ES2019

README.md
[github/personal-website](https://github.com/github/personal-website) has been archived.
=> docs: Remove github/personal-website

README.md
As pointed in #752, #753 and initially reported in #744, there are two ways to configure the permissions. This PR adds links to GitHub's documentation for more details. It also removes the screenshot for configuring the `GITHUB_TOKEN`'s default permissions and points to the documentation instead of sharing the procedure. The idea is to encourage using the `permissions.content` approach which seem more secure.
That's just my 2 cents though.
=> docs: Add GitHub documentation references to permissions

README.md
A working example of good working user-docs and rustdocs published to the root of the GitHub Pages.
https://github.com/paritytech/parity-signer/blob/fcea43ec26bda3c9c2e1f9a4fb1074a3b03b04f4/.github/workflows/docs.yml
Another change is something that I found not obvious from the doc.
=> docs: add rustdoc hint

.github/workflows/codeql.yml, .github/workflows/dependency-review.yml, .github/workflows/dev-image.yml, .github/workflows/label-commenter.yml, .github/workflows/labeler.yml, .github/workflows/pages-status-check.yml, .github/workflows/purge-readme-image-cache.yml, .github/workflows/release.yml, .github/workflows/test.yml, .github/workflows/update-major-tag.yml, README.md
- [starting with 8 of August 2022 support for ubuntu 18.04 is deprecated](https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/)
- [ubuntu 22.04 is generally available](https://github.blog/changelog/2022-08-09-github-actions-ubuntu-22-04-is-now-generally-available-on-github-hosted-runners/)
---
This PR was made as a part of blog post [The strongest principle of the blog's growth lies in the human choice to deploy it](https://dev.to/imomaliev/the-strongest-principle-of-the-blogs-growth-lies-in-the-human-choice-to-deploy-it-3ed9)
=> ci: drop ubuntu-18.04, add 22.04, latest

README.md
As of October 2022, the `set-output` construct is deprecated by GitHub for GitHub Actions. Source:
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
This commit changes the use of the construct for the Sphinx example in the README.md file.
=> docs: replace deprecated set-output

.github/ISSUE_TEMPLATE/config.yml, README.md
This PR fixes a typo I spotted and bumps `hugo` version in the sample script to latest release
=> docs: fix typo, bump hugo version

README.md
Refer to the [official documentation](https://docs.github.com/en/actions/using-jobs/using-conditions-to-control-job-execution#overview).
=> docs: remove braces in if conditions
